#!/bin/csh -f

set DIR = `pwd`
echo
echo $DIR

#directory of excutable

#run options
echo input file $DIR/in-$1
echo output directory $DIR/out-$1
mpirun -np 1 $DIR/cim -d 2 -p 1 1 -i $DIR/in-$1-1 -o $DIR/out-$1-1
mpirun -np 1 $DIR/cim -d 2 -p 1 1 -i $DIR/in-$1-2 -o $DIR/out-$1-2
mpirun -np 1 $DIR/cim -d 2 -p 1 1 -i $DIR/in-$1-3 -o $DIR/out-$1-3
mpirun -np 1 $DIR/cim -d 2 -p 1 1 -i $DIR/in-$1-4 -o $DIR/out-$1-4
