#!/bin/csh -f

set DIR = `pwd`

#directory of excutable
echo $DIR
echo input file $DIR/in-$1

#run options
if ( $#argv != 1 ) then
	echo "Multi-threads"
	echo output directory $DIR/out-$1-$2$3
	@ n = $2 * $3
	mpirun -np $n $DIR/parachute -d 2 -p $2 $3 -i $DIR/in-$1 -o $DIR/out-$1-$2$3
else
	echo "Single-thread"
	echo output directory $DIR/out-$1
	mpirun -np 1 $DIR/parachute -d 2 -p 1 1 -i $DIR/in-$1 -o $DIR/out-$1
endif
