#!/bin/csh -f

set DIR = `pwd`
echo
echo $DIR

#directory of excutable

#run options
echo input file $DIR/in-$1
echo output directory $DIR/out-$1
mpirun -np 1 $DIR/crystal -d 1 -p 1 -i $DIR/in-$1 -o $DIR/out-$1
